name: Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - website/**

permissions:
  contents: read

jobs:
  test:
    name: Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '17']
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Installation
        run: yarn
      - name: Test
        run: yarn test
      - name: TypeCheck website
        run: yarn workspace website typecheck
